export const carOptions= [
    'BMW 1 Series (compact hatchback/sedan)',
    'BMW i7 (electric version of the 7 Series – ultra-premium)',
    'BMW X1 (subcompact luxury SUV)',
    'BMW X2 (sportier compact crossover)',
    'BMW X3 (compact SUV)',
    'BMW X4 (coupe version of X3)',
    'BMW X5 (mid-size luxury SUV)',
    'BMW X6 (coupe version of X5)',
    'BMW X7 (full-size 3-row luxury SUV)',
    'BMW 3 Series (compact executive sedan)',
    'BMW 5 Series (mid-size executive sedan)',
    'Mercedes-Maybach S-Class (ultra-luxury version of S-Class)',
    'Mercedes-Benz GLA (subcompact luxury SUV)',
    'Mercedes-Benz GLB (compact luxury SUV with optional third row)',
    'Mercedes-Benz GLC (compact luxury SUV/coupe)',
    'Mercedes-Benz GLE (mid-size luxury SUV/coupe)',
    'Mercedes-Benz GLS (full-size 3-row luxury SUV)',
    'Mercedes-Maybach GLS (ultra-luxury SUV)',
    'Mercedes-Benz G-Class (G-Wagon)',
    'AMG G63 (high-performance luxury SUV)',
    'G550 (luxury off-road SUV)',
    'Mercedes-Benz CLA Coupe (compact 4-door coupe)',
    'Mercedes-Benz CLS Coupe (sleek 4-door coupe)',
    'Mercedes-Benz E-Class Coupe/Cabriolet',
    'Mercedes-Benz S-Class Coupe/Cabriolet (discontinued but still in demand)',
    'Mercedes-Benz SL Roadster',
    'Mercedes-AMG GT Coupe / Roadster',
    'BMW 3 Series (compact executive sedan)',
    'BMW 5 Series (mid-size executive sedan)',
    'BMW 7 Series (full-size luxury sedan)',
  'BMW XM (flagship high-performance luxury ',
  'BMW 2 Series Coupe/Convertible',
  'BMW 4 Series Coupe/Convertible/Gran Coupe',
  'BMW 8 Series Coupe/Convertible/Gran Coupe',
  'BMW i4 (electric 4-door coupe)',
  'BMW i5 (electric version of 5 Series)',
  'BMW i7 (electric 7 Series)',
  'BMW iX1 (compact electric SUV)',
  'BMW iX3 (electric X3 – not available in all markets)',
  'BMW iX (flagship electric SUV – premium and futuristic)',
  'BMW M3, M4, M5, M8',
  'BMW X5 M, X6 M, XM',
  'BMW M850i / M8 Gran Coupe / Convertible',
  ];